config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  post 'sessions', to: 'sessions#create', as: 'sessions'
  resources :users
  resources :assignments do
    resources :submissions
  end

root 'sessions#new'

end

app/models/submission.rb
class Submission < ActiveRecord::Base
  validates :url, presence: true

  belongs_to :user
  belongs_to :assignment
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_assignment
  before_action :set_submission, only: [:edit, :show]

  def index
    @submissions = @assignment.submissions
  end

  def new
    @submission = Submission.new
  end

  def create
    @submission = @assignment.submissions.create(submission_params)
    if @submission.save
      redirect_to assignments_path, notice: 'Assignment was successfully submitted for review.'
    else
      redirect_to assignment_path(@assignment)
    end
  end

  def edit
  end

  def update
    @submission = Submission.find(params[:id])
    @submission.update(submission_update_params)
    redirect_to assignment_submission_path(@assignment, @submission)
  end

  def show
  end

  private

  def set_assignment
    @assignment = Assignment.find(params[:assignment_id])
  end

  def set_submission
    @submission = @assignment.submissions.find(params[:id])
  end

  def submission_params
    params.require(:submission).permit(:user_id, :assignment_id, :url)
  end

  def submission_update_params
    params.require(:submission).permit(:user_id, :assignment_id, :url, :complete)
  end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper

end

app/views/submissions/_form.html.erb
<%= form_for [@assignment, @submission] do |f| %>
  <% if @submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@submission.errors.count, "error") %> prohibited this completed_assignment from being saved:</h2>

      <ul>
      <% @submission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <% if student? %>
   <fieldset>
     <legend>Submit Assignment for Review</legend>
     <div class="field">
       <%= f.hidden_field :user_id, value: session[:user_id] %>
     </div>
     <div class"row collapse">
       <div class="field large-10 columns">
         <%= f.url_field :url, placeholder: "Paste Github URL here" %>
       </div>
       <div class="large-2 columns">
         <%= f.submit "Submit", class: "button postfix" %>
       </div>
     </div>
     <% end %>
   </fielset>
  <% if teacher? %>
    <div class="field">
      <%= f.hidden_field :user_id, value: session[:student_id] %>
    </div>
    <div>
      Completed to specifications? <%= f.check_box :complete %><br>
      <%= f.submit "Approve" %>
    </div>
  <% end %>
<% end %>

app/views/submissions/edit.html.erb
<h1>Submissions#edit</h1>

<%= form_for [@assignment, @submission] do |f| %>
  <% if @submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@submission.errors.count, "error") %> prohibited this completed_assignment from being saved:</h2>

      <ul>
      <% @submission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    Completed to specifications? <%= f.check_box :complete %><br>
    <%= f.submit "Approve" %>
  </div>
<% end %>

app/views/submissions/index.html.erb
<% @submissions.each do |submission| %>
<p>
  <%=  submission.user.name %>
  <%= link_to "Review", edit_assignment_submission_path(params[:assignment_id], submission) %>
</p>
<% end %>

app/views/submissions/new.html.erb
<h1>Submissions#new</h1>
<p>Find me in app/views/submissions/new.html.erb</p>
<%= render 'form' %>

app/views/submissions/show.html.erb
<h1>Submissions#show</h1>
<p>Find me in app/views/submissions/show.html.erb</p>
<%= @submission.user.name %>
<%= @submission.assignment_id %>
<%= @submission.complete %>